### ISSUE TITLE
File name to define index route at "/"

### ISSUE THREAD

**Issue by leachiM2k** [jsdevel/node-fs-routes#3]
Hello,

I'm trying to use this module, but I can't see any option to define a index-route

* /home.js maps to "/home"
* /search/results.js maps to "/search/results"
* but what maps to "/"?

Is it a missing feature or a wanted scenario to not have this option?

Cheers
Michael

**Comment by jsdevel** [comment]
Sorry for the late reply.  Yes this feature should be supported.  Care to open a PR?
